[package]
name = "hap-mod-image"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hap-common = { path = "../common" }
serde = { workspace = true }
serde_json = { workspace = true }
libc = { workspace = true }
image = { version = "0.25", features = ["png", "jpeg", "gif", "webp", "bmp", "ico", "tiff"] }
imageproc = "0.25"
base64 = "0.22"
kamadak-exif = "0.6"
ab_glyph = "0.2"
