[package]
name = "hap-mod-bluetooth"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hap-common = { path = "../common" }
serde = { workspace = true }
serde_json = { workspace = true }
libc = { workspace = true }
btleplug = "0.11"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }
uuid = "1"
