[package]
name = "hap-mod-clipboard"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hap-common = { path = "../common" }
serde = { workspace = true }
serde_json = { workspace = true }
libc = { workspace = true }
arboard = "3"
base64 = "0.22"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
