[package]
name = "hap-mod-crypto"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hap-common = { path = "../common" }
serde = { workspace = true }
serde_json = { workspace = true }
ring = "0.17"
ed25519-dalek = { version = "2", features = ["rand_core"] }
rsa = { version = "0.9", features = ["sha2"] }
x25519-dalek = { version = "2", features = ["static_secrets"] }
argon2 = "0.5"
bcrypt = "0.17"
aes-gcm = "0.10"
chacha20poly1305 = "0.10"
cbc = { version = "0.1", features = ["alloc"] }
aes = "0.8"
totp-rs = { version = "5", features = ["gen_secret", "otpauth"] }
x509-parser = "0.16"
uuid = { version = "1", features = ["v4", "v7"] }
rand = "0.8"
base64 = "0.22"
data-encoding = "2"
crc32fast = "1"
pem = "3"
getrandom = "0.2"
hmac = "0.12"
sha2 = "0.10"
sha1 = "0.10"
md-5 = "0.10"
sha3 = "0.10"
blake3 = "1"
subtle = "2"
hex = "0.4"
