[package]
name = "hap-mod-fs"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hap-common = { path = "../common" }
serde = { workspace = true }
serde_json = { workspace = true }
libc = { workspace = true }
globset = "0.4"
walkdir = "2"
sha2 = "0.10"
md-5 = "0.10"
hex = "0.4"
infer = "0.19"
base64 = "0.22"
regex = "1"
sysinfo = "0.35"
notify = "7"
fs2 = "0.4"
