[package]
name = "hap-mod-websocket"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hap-common = { path = "../common" }
serde = { workspace = true }
serde_json = { workspace = true }
libc = { workspace = true }
tungstenite = { version = "0.24", features = ["native-tls"] }
base64 = "0.22"
url = "2"
